package org.fullmetalfalcons.scouting.main;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Random;

import javax.swing.JOptionPane;

import org.fullmetalfalcons.scouting.elements.Element;
import org.fullmetalfalcons.scouting.equations.Equation;
import org.fullmetalfalcons.scouting.exceptions.ElementParseException;
import org.fullmetalfalcons.scouting.fileio.Reader;
import org.fullmetalfalcons.scouting.fileio.Writer;
import org.fullmetalfalcons.scouting.teams.Team;

import com.dd.plist.NSDictionary;

/**
 * Team 4557 FullMetalFalcons Scouting Program - Conversion to Excel
 *
 * The program works with the same Config file as the phone app, allowing it to be updated each year with
 * minimal effort.
 *
 * The program then locates plist files generated by the phone app, reads the data inside and exports it to
 * a custom generated Excel Worksheet.
 *
 * You may copy, change, modify, and share this program as you see fit, however you may not sell it
 * This program uses the Apache POI, dd-plist, and expr libraries to function, each with their own licenses.
 *
 * @author Dan Herlihy
 * Created by Dan on 1/11/2016.
 */
public class Main {

    private static final ArrayList<Element> ELEMENTS = new ArrayList<>();
    private static final ArrayList<Team> TEAMS = new ArrayList<>();
    private static final ArrayList<Equation> EQUATIONS = new ArrayList<>();
    //Console spam
    private static final boolean DEBUG = false;

    public static String plistsDir;
    
    //1st location is location of config file
    //2nd argument is location of plist folder
    public static void main(String args[]){
        try {
            //Crash Test Dummy \/ \/ \/
            //String a = args[5];
            //Program needs to be told where to look for the plist files
            if(args.length<2){
                sendError("You have not provided a location for plists or config file");
                System.exit(-1);
            }

            log("Program Starting");
            log("Starting to load configuration");

            //Populates ELEMENTS ArrayList from configuration file
            Reader.loadConfig(args[0]);

            log(ELEMENTS.size() + " elements loaded");

            log("Starting to load plists");

            //Populates TEAMS ArrayList from plist files, passes location of plists
            plistsDir = args[1];
            Reader.loadPlists(plistsDir);

            log(TEAMS.size() + " teams loaded");

            log("Starting to write file");

            //Writes data to Excel spreadsheet
            Writer.write(args.length<3 ? "" :args[2]);

            //Asks user if they would like to open the Excel workbook
            exitDialogue();

            log("Exiting program");

            System.exit(0);
        } catch(Exception e){
            //If something goes horribly wrong and the exception isn't caught somewhere else in the code

            try (InputStream is = Main.class.getResourceAsStream("/org/fullmetalfalcons/scouting/resources/errors.txt");
                 InputStreamReader isr = new InputStreamReader(is);
                 BufferedReader br = new BufferedReader(isr)){

                //This try/catch statement loads an entire text file into memory just so it can randomly select a funny error message
                //Yes, my ego is this enormous
                ArrayList<String> lines = new ArrayList<>();
                String line;
                while ((line=br.readLine())!=null){
                    lines.add(line);
                }

                Random rand = new Random();
                sendError(lines.get(rand.nextInt(lines.size())) + ": " + e.toString());

            } catch (IOException e1) {
                //If my ego for some strange reason gets too big, this is where we admit defeat
                sendError("We tried to be funny and we failed. Anyways, the program crashed: " + e.toString());
            }
            e.printStackTrace();
            System.exit(-1);
        }



    }

    private static void exitDialogue() throws IOException {
        int result = JOptionPane.showConfirmDialog(null, "Results have been saved to \""+ Writer.getResultsFile().getAbsolutePath()+ "\" Would you like to open the workbook now?",
                "Done!", JOptionPane.YES_NO_OPTION);
        if (result==JOptionPane.YES_OPTION){
            try {
                Desktop.getDesktop().open(Writer.getResultsFile());
            }catch (IllegalArgumentException e){
                sendError("Congratulations! You managed damage/lose the results file in the time since it was made!");
            }
        }
    }

    /**
     * Creates an Element from a line provided from the config file
     *
     * @param line The line from the config file
     */
    public static void addElement(String line){

        try {
            //If something is wrong with "line" the new element will thrown an ElementParseException
            Element e = new Element(line);
            debug("Element of type " + e.getType().toString() + " created");
            ELEMENTS.add(e);
        } catch (ElementParseException e) {
            sendError("Config error: " + e.getMessage());
        }
    }

    /**
     * Creates a Team Object which essentially just holds an NSDictionary
     *
     * @param dictionary Holds the key/value pairs for the team
     */
    public static void addTeam(NSDictionary dictionary){
        Team t = new Team(dictionary);
        debug("Team " + t.getValue(Team.NUMBER_KEY) + " loaded");
        TEAMS.add(t);
    }

    public static void addEquation(String line){
        Equation e = new Equation(line);
        debug("Equation " + line + " added");
        EQUATIONS.add(e);

    }

    public static ArrayList<Element> getElements(){
        return ELEMENTS;
    }

    public static ArrayList<Team> getTeams() {
        return TEAMS;
    }

    /**
     * Sends an error message to the user with a JOptionPane
     *
     * @param message error message to send
     */
    public static void sendError(String message){
        try {
            int i = JOptionPane.showConfirmDialog(null, message,
                    "You done messed up", JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
            if (i==JOptionPane.CANCEL_OPTION||i==JOptionPane.CLOSED_OPTION){
                System.exit(-1);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "An error occurred while displaying an error",
                    "Yo Dawg!", JOptionPane.ERROR_MESSAGE);

        }

    }

    public static void debug(String message){
        if (DEBUG){
            System.out.println(message);
        }
    }

    public static void log(String message){
        System.out.println(message);
    }

    public static ArrayList<Equation> getEquations() {
        return EQUATIONS;
    }
}
